### ISSUE TITLE
Examples don't all work

### ISSUE THREAD

**Issue by iplayfast** [doug-moen/curv#7] opened 2017-07-13 15:39 UTC
I've been playing with your code but finding that not all the examples work, some just display a coloured screen.
Ones that have problems:
engrave.curv just shows a light blue.
gyroid.curv just shows a olive green
lathe.curv just shows a light blue
morph.curv just shows a light blue
neovius.curv shows the olive green
pancake.curv shows the olive green
plato.curv shows the light blue
rainbow.curv shows the light blue
rbgsphere.curv shows the light blue
rounded.curv shows the olive green
schartz.curv shows a red
shreks_donut shows the light blue
sinewaves.curv shows the light blue
smoke3.curv  shows the light blue (however smoke works fine).
sterographic.curv shows the light blue
tor.curv shows the light blue
twist.curv shows the olive green

all other examples seem to work as expected. I'm using linux mint 18.2, nvidia driver glslViewer compiled from github.
Do these work for you?

**Comment by doug-moen** [comment] 2017-07-13 16:19
For engrave.curv, the bug is that the 3D viewer does not yet automatically zoom the view to display the shape at the correct scale. You need to "zoom out" using the mouse scroll wheel, or trackpad equivalent.

However, it looks like you are having problems with all of the 3D models.

This sounds like a duplicate of #3. You need to compile the glslViewer from my github repository, not from the original author's.
git clone https://github.com/doug-moen/glslViewer.git

If that's not the problem, then: Which nvidia card are you using? I recommend the latest proprietary driver from nVidia, not the open source driver.

**Comment by iplayfast** [comment] 2017-07-13 17:04
I didn't notice your glslViewer it seems to have solved the problem. Might be a good idea just to copy that code into curv, or make a comment in the readme about it.
Thanks for the quick response.

**Closed** 2017-07-13 17:05 UTC
